const BANCOS = [
  'Banco Confederado',
  'Banco Monagas',
  'Fondo Común Entidad de Ahorro y Préstamo',
  'Corp Banca',
  'Banco Noroco',
  'La Primera Entidad de Ahorro y Préstamo',
  'Banco de Coro',
  'Banco Occidental de Descuento',
  'La Vivienda Entidad de Ahorro y Préstamo',
  'Banco de Lara',
  'Banco Plaza C.A.',
  'Mi Casa Entidad de Ahorro y Préstamo',
  'Banco de Venezuela Grupo Santander',
  'Banco Popular y de los Andes, C.A.',
  'Miranda Entidad de Ahorro y Préstamo',
  'Banco del Caribe',
  'Banco Provincial',
  'Oriente Entidad de Ahorro y Préstamo',
  'Banco del Orinoco Banco Universal',
  'Banco República',
  'Pro Vivienda Entidad de Ahorro y Préstamo',
  'Banco do Brasil',
  'Banco Sofitasa',
  'Valencia Entidad de Ahorro y Préstamo',
  'ABN - AMRO Bank',
  'Banco Exterior Banco Universal',
  'Standard Chartered',
  'Banesco Banca Universal',
  'Banco Federal',
  'Banco Tequendama',
  'Banfoandes Banco de Fomento Regional de los Andes',
  'Banco Fivenez',
  'Banco Unión',
  'Banco Canarias de Venezuela',
  'Banco Ganadero',
  'Banco Venezolano de Crédito',
  'Banco Capital',
  'Banco Guayana, C.A.',
  'Caja Familia',
  'Banco Caracas',
  'Banco Industrial de Venezuela',
  'Casa Propia Entidad de Ahorro y Préstamo',
  'Banco Caroní Banco Universal',
  'IMCP Instituto Municipal de Crédito Popular',
  'Central Entidad de Ahorro y Préstamo',
  'Cavendes',
  'Inter Bank Banco Universal',
  'Del Centro, C.A. Entidad de Ahorro y Préstamo',
  'Citibank',
  'Banco Mercantil Banco Universal',
  'Del Sur Entidad de Ahorro y Préstamo',
  'Banco del Pueblo'
]

export async function seedBancos(knex) {
  await knex('bancos').insert(BANCOS.map((nombre) => ({ nombre }))).onConflict('nombre').ignore()
}
